// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: monitor

#include "../ui.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <sys/statvfs.h>

void time_timer_cb(lv_timer_t * timer);
const char* DAY[]={"Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"};
const char* MONTH[]= {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};
char dataTimeString[25];

void ui_homeScreen_screen_init(void)
{
ui_homeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_homeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_homeScreen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_homeScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_homeScreen, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_homeScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_toolbar = lv_obj_create(ui_homeScreen);
lv_obj_set_height( ui_toolbar, 50);
lv_obj_set_width( ui_toolbar, lv_pct(100));
lv_obj_set_align( ui_toolbar, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_toolbar,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_toolbar, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_toolbar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_toolbar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_toolbar, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_toolbar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_toolbar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_toolbar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_toolbar, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_toolbar, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_systemTimeLabel = lv_label_create(ui_toolbar);
lv_obj_set_width( ui_systemTimeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_systemTimeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_systemTimeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_systemTimeLabel,"24 October 2023 : 18:55:23");
lv_obj_set_style_text_color(ui_systemTimeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_systemTimeLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

static uint32_t user_data = 10;
lv_timer_t * time_timer = lv_timer_create(time_timer_cb, 1,  &user_data);

}

void time_timer_cb(lv_timer_t * timer)
{

    time_t t = time(NULL);
    struct tm *local = localtime(&t);

    sprintf(dataTimeString, "%s\n%s %02d %04d : %02d:%02d:%02d", DAY[local->tm_wday], MONTH[local->tm_mon], local->tm_mday, local->tm_year + 1900, local->tm_hour, local->tm_min, local->tm_sec);
    lv_label_set_text(ui_systemTimeLabel, dataTimeString);
}
