// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: monitor

#include "../ui.h"

void ui_welcomeScreen_screen_init(void)
{
ui_welcomeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_welcomeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_welcomeScreen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_welcomeScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_welcomeScreen, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_welcomeScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_header = lv_obj_create(ui_welcomeScreen);
lv_obj_set_width( ui_header, lv_pct(100));
lv_obj_set_height( ui_header, lv_pct(30));
lv_obj_set_align( ui_header, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_header,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_header, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_header, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_header, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_body = lv_obj_create(ui_welcomeScreen);
lv_obj_set_width( ui_body, lv_pct(100));
lv_obj_set_height( ui_body, lv_pct(30));
lv_obj_set_align( ui_body, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_body,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_body, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_body, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_body, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_body, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_welcomeTitle = lv_label_create(ui_body);
lv_obj_set_width( ui_welcomeTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_welcomeTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_welcomeTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_welcomeTitle,"Home monitor");
lv_obj_set_style_text_color(ui_welcomeTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_welcomeTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_welcomeTitle, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_footer = lv_obj_create(ui_welcomeScreen);
lv_obj_set_width( ui_footer, lv_pct(100));
lv_obj_set_height( ui_footer, lv_pct(30));
lv_obj_set_align( ui_footer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_footer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_footer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_footer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_footer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_footer, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_footer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_footer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_getStartedButton = lv_btn_create(ui_footer);
lv_obj_set_height( ui_getStartedButton, 50);
lv_obj_set_width( ui_getStartedButton, lv_pct(50));
lv_obj_set_align( ui_getStartedButton, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_getStartedButton,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_getStartedButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_getStartedButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_getStartedButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_getStartedButtonTitle = lv_label_create(ui_getStartedButton);
lv_obj_set_width( ui_getStartedButtonTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_getStartedButtonTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_getStartedButtonTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_getStartedButtonTitle,"Get started");

lv_obj_add_event_cb(ui_getStartedButton, ui_event_getStartedButton, LV_EVENT_ALL, NULL);

}
