// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: monitor

#ifndef _MONITOR_UI_H
#define _MONITOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_welcomeScreen
void ui_welcomeScreen_screen_init(void);
extern lv_obj_t *ui_welcomeScreen;
extern lv_obj_t *ui_header;
extern lv_obj_t *ui_body;
extern lv_obj_t *ui_welcomeTitle;
extern lv_obj_t *ui_footer;
void ui_event_getStartedButton( lv_event_t * e);
extern lv_obj_t *ui_getStartedButton;
extern lv_obj_t *ui_getStartedButtonTitle;
// SCREEN: ui_homeScreen
void ui_homeScreen_screen_init(void);
extern lv_obj_t *ui_homeScreen;
extern lv_obj_t *ui_toolbar;
extern lv_obj_t *ui_systemTimeLabel;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
